import subprocess, time, psutil
import io
import contextlib
from codecarbon import EmissionsTracker
import multiprocessing
import math, random, itertools
import os

# Safe built-ins for sanbox
safe_builtins = {
    "print": print,
    "range": range,
    "len": len,
    "sum": sum,
    "min": min,
    "max": max,
    "abs": abs,
    "sorted": sorted,
    "enumerate": enumerate,
    "zip": zip,
}

# Allowed modules
safe_modules = {
    "math": math,
    "random": random,
    "itertools": itertools,
}

def execution_worker(code,queue):
    #executes code in separate process
    f = io.StringIO()
    with contextlib.redirect_stdout(f):
        # Create isolated globals dict with safe built-ins and modules
        sandbox_globals = {"__builtins__":safe_builtins}
        sandbox_globals.update(safe_modules)
        #using CodeCarbon to track emissions
        carbon_tracker = EmissionsTracker(
            output_file="execution_emissions.csv",
            save_to_file=True,
            measure_power_secs=1,
            log_level="error",
            tracking_mode="machine",)
        try:
            carbon_tracker.start()
            process = psutil.Process(os.getpid())
            mem_usage_before = process.memory_info().rss 
            exec(code, sandbox_globals)
            mem_usage_after = process.memory_info().rss
            max_memory_used = mem_usage_after - mem_usage_before
            emissions = carbon_tracker.stop()
            queue.put((f.getvalue(), emissions, max_memory_used/(1024**2)))#convert vto MB
        except Exception as e:
            carbon_tracker.stop()
            queue.put((f"Error: {e}", None))


#run the code generated by the llm in a sandbox and measure time and emissions
def execute_generated_code(code, timeout = 10):
    #work through queue of generated code to execute
    queue = multiprocessing.Queue()
    process = multiprocessing.Process(target=execution_worker, args=(code,queue))
    process.start()
    process.join(timeout)

    if process.is_alive():
        process.terminate()
        process.join()
        return "timed out", None
    if queue.empty():
        return "no output", None
    output, emissions, memory_mb = queue.get()
    return output, emissions, memory_mb

#safety for windows ->only run multiprocessing code under main guard
if __name__ == "__main__":
    test_code = """
a = [i for i in range(1000000)]
print('Hello from sandbox!')
"""
    output, emissions, memory_mb = execute_generated_code(test_code)
    print("--- Sandbox Test ---")
    print("Output:", output)
    print("Emissions (kg CO₂):", emissions)
    print("Memory used (MB):", memory_mb)