import subprocess, time, psutil
import io
import contextlib
from codecarbon import EmissionsTracker
import tracemalloc
import multiprocessing
import math, random, itertools
import os
import re


# safe built-ins for sanbox
safe_builtins = {
 "abs": abs, "all": all, "any": any, "bool": bool, "dict": dict, "enumerate": enumerate,
    "float": float, "int": int, "len": len, "list": list, "max": max, "min": min,
    "print": print, "range": range, "reversed": reversed, "set": set, "str": str, "sum": sum, "zip": zip
}

# allowed modules
safe_modules = {
    "math": math,
    "random": random,
    "itertools": itertools,
    "re":re,
}

def execution_worker(code,queue):
    #executes code in separate process
    f = io.StringIO()
    emissions = None
    mem_mb = 0.0
    with contextlib.redirect_stdout(f):
        # create isolated globals dict with safe built-ins and modules
        sandbox_globals = {"__builtins__":safe_builtins}
        sandbox_globals.update(safe_modules)
        #using CodeCarbon to track emissions
        carbon_tracker = EmissionsTracker(
            output_file="execution_emissions.csv",
            save_to_file=True,
            measure_power_secs=1,
            log_level="error",
            tracking_mode="machine",)
        try:
            tracemalloc.start()
            carbon_tracker.start()
            process = psutil.Process(os.getpid())
            exec(code, sandbox_globals)
            current, peak = tracemalloc.get_traced_memory()
            tracemalloc.stop()
            mem_mb = peak/(1024**2)
            emissions = carbon_tracker.stop()
            queue.put((f.getvalue(), emissions, mem_mb))#convert to MB
        except Exception as e:
            emissions = carbon_tracker.stop()
            tracemalloc.stop()
            queue.put((f"Error: {e}", emissions, mem_mb))


#run the code generated by the llm in a sandbox and measure time and emissions
def execute_generated_code(code, timeout = 10):
    #work through queue of generated code to execute
    queue = multiprocessing.Queue()
    process = multiprocessing.Process(target=execution_worker, args=(code,queue))
    process.start()
    process.join(timeout)

    if process.is_alive():
        process.terminate()
        process.join()
        return "timed out", None, None
    if queue.empty():
        if process.exitcode not in (0, None):
            return f"worker exited with code {process.exitcode}", None, None
        return "no output", None, None
    try:
        output, emissions, memory_mb = queue.get_nowait()
    except Exception:
        return "malformed worker result", None, None
    return output, emissions, memory_mb
 

